export const FOR_PROFIT_MAIN = [
    'Active Life',
    'Arts & Entertainment',
    'Automotive',
    'Beauty & Spas',
    'Education',
    'Event Planning & Services',
    'Financial Services',
    'Food',
    'Health & Medical',
    'Home Services',
    'Hotels & Travel',
    'Local Services',
    'Mass Media',
    'Nightlife',
    'Pets',
    'Professional Services',
    'Public Services & Government',
    'Real Estate',
    'Religious Organization',
    'Restaurants',
    'Shopping',
    'Social Media',
] as const

export const FOR_PROFIT_AREAS: Record<string, { options: string[]; includeOther: boolean; specialTextOnly?: boolean }> = {
    'Active Life': { options: ['Fitness & Instruction', 'Boxing', 'Cardio Classes', 'Gyms', 'Martial Arts', 'Meditation Centers', 'Self-Defense Classes', 'Yoga'], includeOther: true },
    'Arts & Entertainment': { options: ['Art Galleries', 'Artists', 'Entertainment', 'Performing Arts', 'Psychics', 'Wineries'], includeOther: true },
    Automotive: {
        options: [
            'Auto Glass Services',
            'Auto Customization',
            'Auto-Detailing',
            'Car Window Tinting',
            'Auto Parts & Supplies',
            'Motorcycle Parts & Supplies',
            'Auto Repair',
            'Auto Upholstery',
            'Car Dealers',
            'Car Wash',
            'Commercial Truck Dealers',
            'Commercial Truck Repair',
            'Towing',
            'Trucking Services',
            'Wheel & Rim Repair',
            'Windshield Installation & Repair',
        ],
        includeOther: true,
    },
    'Beauty & Spas': {
        options: [
            'Barbers',
            'Cosmetics & Beauty Supply',
            'Eyebrow Services',
            'Eyelash Service',
            'Hair Extensions',
            'Sugaring',
            'Threading Services',
            'Waxing',
            'Hair Salons',
            'Blow Dry/Out Services',
            'Hair Extensions',
            'Hair Stylists',
            'Kids Hair Salons',
            'Men’s Hair Salons',
            'Makeup Artists',
            'Massage',
            'Nail Salons',
            'Permanent Makeup',
            'Skin Care',
            'Tattoo',
            'Teeth Whitening',
        ],
        includeOther: true,
    },
    Education: { options: ['Adult Education', 'Art Classes', 'College Counseling', 'Educational Services', 'Preschools', 'Private Tutors', 'Childbirth Education', 'Parenting Classes', 'Test Preparation'], includeOther: true },
    'Event Planning & Services': {
        options: [
            'Bartenders',
            'Cards & Stationery',
            'Caterers',
            'DJs',
            'Henna Artists',
            'Magicians',
            'Musicians',
            'Party & Event Planning',
            'Audio/Visual Equipment Rental',
            'Party Supplies',
            'Personal Chefs',
            'Photographers',
            'Sommelier Services',
            'Valet Services',
            'Venues & Event Spaces',
            'Videographers',
        ],
        includeOther: true,
    },
    'Financial Services': { options: ['Business Financing', 'Financial Advising', 'Insurance', 'Auto Insurance', 'Home & Rental Insurance', 'Life Insurance', 'Investing', 'Mortgage Lenders', 'Tax Services'], includeOther: true },
    Food: {
        options: [
            'Bakeries',
            'Coffee & Tea',
            'Custom Cakes & Cupcakes',
            'Desserts',
            'Empanadas',
            'Food Trucks',
            'Grocery',
            'Ice Cream & Frozen Yogurt',
            'Juice Bars & Smoothies',
            'Organic Stores',
            'Patisserie/Cake Shop',
            'Popcorn Shop',
            'Specialty Food',
            'Chocolatiers & Shops',
            'Fruits & Veggies',
            'Health Markets',
            'Herbs & Spices',
            'Street Vendors',
        ],
        includeOther: true,
    },
    'Health & Medical': {
        options: [
            'Alternative Medicine',
            'Animal Assisted Therapy',
            'Body Contouring',
            'Cannabis Clinics',
            'Cannabis Tours',
            'Chiropractors',
            'Counseling & Mental Health',
            'Psychologists',
            'Cosmetic Dentists',
            'Dietitians',
            'Addiction Medicine',
            'Addiction Treatment Services',
            'Naturopathic/Holistic',
            'Doulas',
            'Health Coach',
            'Massage Therapy',
            'Nutritionists',
            'Personal Care Services',
            'Physical Therapy',
            'Rehabilitation Center',
            'Weight Loss Centers',
        ],
        includeOther: true,
    },
    'Home Services': {
        options: [
            'Building Supplies',
            'Cabinetry',
            'Carpenters',
            'Carpet Installation',
            'Carpeting',
            'Chimney Sweeps',
            'Contractors',
            'Decks & Railing',
            'Drywall Installation & Repair',
            'Electricians',
            'Fences & Gates',
            'Fire Protection Services',
            'Flooring',
            'Gardeners',
            'Glass & Mirrors',
            'Handyman',
            'Heating & Air Conditioning/HVAC',
            'Home Cleaning',
            'Interior Design',
            'Keys & Locksmiths',
            'Landscaping',
            'Lawn Services',
            'Lighting Fixtures & Equipment',
            'Mobile Home Repair',
            'Movers',
            'Painters',
            'Plumbing',
            'Pool Cleaners',
            'Pressure Washers',
            'Real Estate',
            'Roofing',
            'Siding',
            'Solar Installation',
            'Technology Services',
            'Window Washing',
        ],
        includeOther: true,
    },
    'Hotels & Travel': { options: ['Car Rental', 'Tours', 'Hotels'], includeOther: true },
    'Local Services': {
        options: [
            'Appliances & Repair',
            'Awnings',
            'Bike Repair/Maintenance',
            'Carpet Cleaning',
            'Carpet Dyeing',
            'Child Care & Day Care',
            'Community Book Box',
            'Community Gardens',
            'Community Service/Non-Profit',
            'Food Banks',
            'Couriers & Delivery Services',
            'Elder Care Planning',
            'Electronics Repair',
            'Furniture Repair',
            'Furniture Reupholstery',
            'IT Services & Computer Repair',
            'Mobile Phone Repair',
            'Janitorial Services',
            'Jewelry Repair',
            'Telecommunications',
            'Laundry Services',
            'Dry Cleaning',
            'Laundromat',
            'Machine & Tool Rental',
            'Musical Instrument Services',
            'Nanny Services',
            'Notaries',
            'Pest Control',
            'Printing Services',
            'Recording & Rehearsal Studios',
            'Screen Printing',
            'Screen Printing/T-Shirt Printing',
            'Shoe Repair',
            'Tailor',
            'Repairs',
            'Alterations',
            'Design',
            'Waste Management',
        ],
        includeOther: true,
    },
    'Mass Media': { options: ['Print Media', 'News Website', 'Radio Stations', 'Media Production', 'Television Stations'], includeOther: true },
    Nightlife: { options: ['Bars', 'Music Venues'], includeOther: true },
    Pets: { options: ['Pet Services', 'Dog Walkers', 'Pet Groomers', 'Pet Photography', 'Pet Sitting', 'Pet Stores'], includeOther: true },
    'Professional Services': {
        options: [
            'Consulting',
            'Accountants',
            'Advertising',
            'Publishing',
            'Billing Services',
            'Prison Consultant',
            'Bookkeepers',
            'Business Consulting',
            'Career Counseling',
            'Commissioned Artists',
            'Editorial Services',
            'Entrepreneurial Advisement',
            'Employment Agencies',
            'Graphic Design',
            'Transitional Housing',
            'Internet and Website Services',
            'Lawyers',
            'Legal Services',
            'Life Coach',
            'Marketing',
            'Matchmakers',
            'Music Production Services',
            'Office Cleaning',
            'Payroll Services',
            'Personal Assistants',
            'Private Investigation',
            'Product Design',
            'Professional & Vocational Training',
            'Public Relations',
            'Security Services',
            'Software Development',
            'Tax Services',
            'Video/Film Production',
            'Web Design',
            'Wholesalers',
            'Workplace Coach',
            'Restaurant Supplies',
        ],
        includeOther: true,
    },
    'Public Services & Government': { options: ['Community Centers', 'Political Candidate', 'Libraries'], includeOther: true },
    'Real Estate': { options: ['Property Owner', 'Home Staging', 'Mortgage Brokers', 'Real Estate Agents', 'Real Estate Photography', 'Shared Office Spaces'], includeOther: true },
    'Religious Organization': { options: [], includeOther: false, specialTextOnly: true },
    Restaurants: { options: ['Cafes', 'Delis', 'Diners', 'Food Court', 'Food Stands', 'Gluten-Free', 'Pizza', 'Vegan', 'Vegetarian', 'Specialty Cuisines'], includeOther: true },
    Shopping: {
        options: [
            'Adult',
            'Antiques',
            'Art Galleries',
            'Arts & Crafts',
            'Art Supplies',
            'Cards & Stationery',
            'Cooking Classes',
            'Baby Gear & Furniture',
            'Books, Mags, Music & Video',
            'Bookstores',
            'Music & DVDs',
            'Newspapers & Magazines',
            'Video Game Stores',
            'Bridal',
            'Cannabis Dispensaries',
            'Computers',
            'Cosmetics & Beauty Supply',
            'Customized Merchandise',
            'Electronics',
            'Eyewear & Opticians',
            'Sunglasses',
            'Fashion',
            'Accessories',
            'Children’s Clothing',
            'Formal Wear',
            'Hats',
            'Lingerie',
            'Maternity Wear',
            'Men’s Clothing',
            'Plus Size Fashion',
            'Shoe/Sneakers',
            'Sports Wear',
            'Swimwear',
            'Used, Vintage & Consignment',
            'Women’s Clothing',
            'Fitness/Exercise Equipment',
            'Flowers & Gifts',
            'Cards & Stationery',
            'Florists',
            'Gift Shops',
            'High Fidelity Audio Equipment',
            'Home & Garden',
            'Appliances',
            'Candle Stores',
            'Furniture Stores',
            'Holiday Decorations',
            'Home Decor',
            'Hot Tub & Pool',
            'Kitchen & Bath',
            'Kitchen Supplies',
            'Nurseries & Gardening',
            'Outdoor Furniture Stores',
            'Rugs',
            'Jewelry',
            'Mobile Phone Accessories',
            'Mobile Phones',
            'Motorcycle Gear',
            'Musical Instruments & Teachers',
            'Office Equipment',
            'Packing Supplies',
            'Photography Stores & Services',
            'Safety Equipment',
            'Souvenir Shops',
            'Bikes',
            'Outdoor Gear',
            'Tabletop Games',
            'Teacher Supplies',
            'Tobacco Shops',
            'Toy Stores',
            'Used Bookstore',
            'Vitamins & Supplements',
            'Watches',
            'Wholesale Stores',
            'Wigs',
        ],
        includeOther: true,
    },
    'Social Media': { options: ['Influencer', 'Marketing'], includeOther: true },
}
