export const NON_PROFIT_MAIN = ['Non-Profit for Alternatives to Incarceration', 'Non-Profit Work Regarding Conditions of Confinement', 'Reentry', 'Education the Public/Civic Engagement', 'Advocacy and Policy'] as const

export const NON_PROFIT_AREAS: Record<string, { options: string[]; includeOther: boolean }> = {
    'Non-Profit for Alternatives to Incarceration': {
        options: [
            'Civil Commitments/Sex Offender Registry',
            'Civil Forfeiture',
            'Community Service',
            'Conflict Resolution',
            'Community-Based Substance Use Disorder Treatment',
            'Court Advocacy Services',
            'Diversion Programs',
            'Drug Courts',
            'Fines & Restitution',
            'Gang and Violence Intervention',
            'House Arrest',
            'Policing',
            'Pretrial Services/Probation',
            'Preventative Programs/Services',
            'Psychiatric Treatment',
            'Restorative Justice',
            'Training, Mentoring, and Jobs for Young Adults',
            'Young Adult Mentoring',
        ],
        includeOther: true,
    },
    'Non-Profit Work Regarding Conditions of Confinement': {
        options: [
            'Death Penalty',
            'Extreme Weather/Natural Disasters',
            'Forced Labor',
            'Juvenile/Youth Justice',
            'Participatory Defense',
            'Dignity for Incarcerated Women and Girls',
            'Court and Legal Support',
            'Sexual Assault, Sexual Harassment, Sexual Abuse',
            'Solitary Confinement',
            'Wrongful Convictions',
            'Education services',
            'Health Services',
            'Financial assistance',
        ],
        includeOther: true,
    },
    Reentry: {
        options: [
            'Educational classes/ certificate',
            'Financial Coaching',
            'Starting Small Business. Self Employment',
            'Housing',
            'Probation/Parole/Community Corrections',
            'Life Coaching',
            'Education for Newly Released and Formerly Incarcerated People',
            'Wraparound Services',
            'Family Services',
            'Family Reunification',
            'Professional Development',
            'Leadership Development',
            'Trauma-informed Care',
            'Counseling Services',
            'Health Services',
            'Community Services',
        ],
        includeOther: true,
    },
    'Education the Public/Civic Engagement': {
        options: ['Census/Voting Rights', 'Clemency', 'Covid-19', 'Impact litigation', 'Racial Justice', 'Reproductive Justice', 'Solitary Confinement', 'Forced Family Separation', 'Shackling', 'Training Programs', 'Criminal Justice', 'Humanizing Language'],
        includeOther: true,
    },
    'Advocacy and Policy': {
        options: [
            'Census/Voting Rights',
            'Clemency',
            'Community Corrections',
            'Community Organizing',
            'Covid-19',
            'Impact litigation',
            'Racial Justice',
            'Restorative Justice',
            'Reproductive Justice',
            'Solitary Confinement',
            'Forced Family Separation',
            'Shackling',
            'Fines & Fees',
            'Bail Reform',
            'Immigration',
            'Elder Incarceration',
            'Parole and Probation Reform',
            'Smart on Crime Initiative',
            'Policing',
            'Prison Abolition',
            'Pardon and Clemency',
            'Wrongful Convictions',
            'Thirteenth Amendment',
            'Drug Sentencing',
            'LGBTQ+ Support',
            'Reentry',
            'Storytelling',
            'Youth Empowerment and Leadership Development',
            'Legal Aid & Defense Services',
            'Sentencing Reform',
            "Women's Issues",
            'Sex Work',
            'Crypto Reform',
        ],
        includeOther: true,
    },
}
